recur/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers
from recurapp import views

router = routers.DefaultRouter()
router.register('users', views.UserViewSet)
router.register('groups', views.GroupViewSet)
router.register('foods', views.food_search)

urlpatterns = [
    path('', include('recurapp.urls')),
    path('accounts/', include('allauth.urls')),
    path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls')),
    path('admin/', admin.site.urls, name='admin'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

recurapp/urls.py
from django.urls import path
from . import views
from django.contrib import admin

app_name = 'recurapp'


urlpatterns = [
    path('', views.home, name='home'),
    path('desc_search/', views.desc_search, name='desc_search'),
    path('desc_search/refuse/<int:food_code>/', views.ndb_search, name='ndb_search'),
    path('desc_search/<int:food_code>/', views.nutrient_search, name='nutrient_search'),
    path('calorieDisplay/', views.calorieDisplay, name='calorieDisplay'),
    path('calorieCreate/', views.calorieCreate, name='calorieCreate'),
    path('accounts/profile/', views.profile, name='profile'),
    path('create_meal/', views.create_meal, name='create_meal'),
    path('admin/', admin.site.urls, name='admin'),
]

templates/bootstrap4/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'recurapp:home' %}">Testing</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item {% if home %}active{% endif %}">
        <a class="nav-link" href="{% url 'recurapp:home' %}">Home<span class="sr-only">{% if home %}(current){% endif %}</span></a>
      </li>
    </ul>
    <ul class="navbar-nav ml-auto">
    {% if user.is_authenticated %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'account_email' %}">Change E-mail</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'account_logout' %}">Sign Out</a>
        </li>
    {% else %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'account_login' %}">Sign In</a>
        </li>
        <li class="nav-item">
           <a class="nav-link" href="{% url 'account_signup' %}">Sign Up</a>
        </li>
    {% endif %}
    </ul>
  </div>
</nav>
{% if messages %}
    <div class="alert alert-primary alert-dismissible fade show" role="alert">
        <ul>
            {% for message in messages %}
                <li>{{message}}</li>
            {% endfor %}
        </ul>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
{% endif %}

templates/bootstrap4/scripts.html
 {% load static %}
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

    <!-- Icons -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.27.0/feather.min.js"></script>
    <script>
      feather.replace()
    </script>

    <!-- Graphs -->
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
    <script>
      var ctx = document.getElementById("myChart");
      var myChart = new Chart(ctx, {
        type: 'line',
        data: {
          labels: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
          datasets: [{
            data: [15339, 21345, 18483, 24003, 23489, 24092, 12034],
            lineTension: 0,
            backgroundColor: 'transparent',
            borderColor: '#007bff',
            borderWidth: 4,
            pointBackgroundColor: '#007bff'
          }]
        },
        options: {
          scales: {
            yAxes: [{
              ticks: {
                beginAtZero: false
              }
            }]
          },
          legend: {
            display: false,
          }
        }
      });
    </script>

templates/bootstrap4/sidebar.html
{% load static %}
    <div class="sidebar">
        <a {% if home %}class="active"{% endif %} href="{% url 'recurapp:home' %}">Home</a>
        <a {% if nutsearch %}class="active"{% endif %} href="{% url 'recurapp:desc_search' %}">Food Search</a>
        <a {% if user_calories %}class="active"{% endif %} href="{% url 'recurapp:calorieDisplay' %}">User Calories</a>
    </div>