recur/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers
from recurapp import views

router = routers.DefaultRouter()
router.register('users', views.UserViewSet)
router.register('groups', views.GroupViewSet)
router.register('foods', views.food_search)

urlpatterns = [
    path('', include('recurapp.urls')),
    path('accounts/', include('allauth.urls')),
    path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls')),
    path('admin/', admin.site.urls, name='admin'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

recurapp/urls.py
from django.urls import path
from . import views
from django.contrib import admin

app_name = 'recurapp'


urlpatterns = [
    path('', views.home, name='home'),
    path('desc_search/', views.desc_search, name='desc_search'),
    path('desc_search/refuse/<int:food_code>/', views.ndb_search, name='ndb_search'),
    path('desc_search/<int:food_code>/', views.nutrient_search, name='nutrient_search'),
    path('calorieDisplay/', views.calorieDisplay, name='calorieDisplay'),
    path('calorieCreate/', views.calorieCreate, name='calorieCreate'),
    path('accounts/profile/', views.profile, name='profile'),
    path('create_meal/', views.create_meal, name='create_meal'),
    path('admin/', admin.site.urls, name='admin'),
]

customProfile/models.py
from django.db import models
from django.contrib.auth.models import User
from recurapp.models import MainDesc, Foodweights


class CustomUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    SEX_CHOICES = [
        (5, "Male"),
        (-161, "Female")
    ]
    sex = models.IntegerField(choices=SEX_CHOICES,
                              default=5)
    age = models.SmallIntegerField(blank=True, null=True)
    weight = models.FloatField(blank=True, null=True)
    WEIGHT_UNIT_CHOICES = [
        (2.20462, "Pounds"),
        (1, "Kilograms"),
    ]
    weightUnit = models.FloatField(choices=WEIGHT_UNIT_CHOICES,
                                   default=1)
    height = models.FloatField(blank=True, null=True)
    HEIGHT_UNIT_CHOICES = [
        (2.54, "Inches"),
        (1, "Centimeters"),
    ]
    heightUnit = models.FloatField(choices=HEIGHT_UNIT_CHOICES,
                                   default=1)
    ACTIVITY_LEVEL_CHOICES = [
        (1.2, "Sedentary"),
        (1.375, "Light Activity"),
        (1.55, "Moderately Active"),
        (1.725, "Very Active"),
        (1.9, "Extremely Active"),
    ]
    activityLevel = models.FloatField(choices=ACTIVITY_LEVEL_CHOICES,
                                      default=1.2)

    def get_calories(self):
        return int(((10 * (self.weight / self.weightUnit)) + (6.25 * (self.height * self.heightUnit)) - (
                5 * self.age) + self.sex) * self.activityLevel)

    def __str__(self):
        return f"{self.user.username} Custom Profile"


class UserConsumedFood(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    day = models.DateTimeField(auto_now_add=True)
    MEAL_CHOICES = [
        ("b", "Breakfast"),
        ("l", "Lunch"),
        ("d", "Dinner"),
        ("s", "Snack")
    ]
    meal = models.CharField(choices=MEAL_CHOICES,
                            default='b',
                            max_length=2)
    food = models.ForeignKey(MainDesc, null=True, blank=True, on_delete=models.SET_NULL)
    servingSize = models.ForeignKey(Foodweights, null=True, blank=True, on_delete=models.SET_NULL)
    takenPortion = models.FloatField(default=1.0)
    returnedPortion = models.FloatField(default=0.0)


class UserWeights(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    oldWeights = models.FloatField()

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block head_title %}{% endblock %}</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.1/examples/dashboard/">

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "css/sidebar.css" %}">
    <!-- Custom styles for this template -->
      {% block extra_head %}
      {% endblock %}
  </head>
<body>

        {% block body %}
        {% include "bootstrap4/navbar.html" %}
        <div class="container-fluid">
            <div class="row">
                <div class="col-fluid">
                    {% include "bootstrap4/sidebar.html" %}
                </div>
                <div class="col p-5">
                    {% block content %}
                    {% endblock %}
                    {% endblock %}
                    {% block extra_body %}
                    {% endblock %}
                </div>
            </div>
        </div>
    {% include "bootstrap4/scripts.html" %}
    {% block extra_scripts %}
    {% endblock %}
</body>
</html>

templates/calorie.html
{% extends 'base.html' %}

{% load static %}
{% block content %}
<div class="card">
    <div class="row">
        <div class="col-4">
            <img src="{% static "sitepic/active.jpg" %}" class="card-img" alt="girl running image">
        </div>
        <div class="col-8">
            <h5 class="card-title">Calories</h5>
                <div class="row">
                    <p class="col-2">Age:</p>
                    <div class="col-3">
                        {{ customUser.age }}
                    </div>
                    <p class="col-2">Gender:</p>
                    <div class="col-3">
                        {{ customUser.get_sex_display }}
                    </div>
                </div>
                <div class="row">
                    <p class="col-2">Weight:</p>
                    <div class="col-3">
                        {{ customUser.weight }}
                    </div>
                    <p class="col-2">Weight Unit:</p>
                    <div class="col-3">
                        {{ customUser.get_weightUnit_display }}
                    </div>
                </div>
                <div class="row">
                    <p class="col-2">Height:</p>
                    <div class="col-3">
                        {{ customUser.height }}
                    </div>
                    <label class="col-2">Height Unit:</label>
                    <div class="col-3">
                        {{ customUser.get_heightUnit_display }}
                    </div>
                </div>
                <div class="row">
                    <p class="col-2">Activity Level:</p>
                    <div class="col-3">
                        {{ customUser.get_activityLevel_display }}
                    </div>
                    <div class="col-4">
                        <p>{{ calories }} Calories Per Day</p>
                    </div>
                </div>
                 <div class="row justify-content-md-center">
                    <div class="col-1">
                        <a href="{% url 'recurapp:calorieCreate' %}" class="btn btn-primary">Update</a>
                    </div>
                </div>
        </div>
    </div>
</div>
{% endblock %}

templates/calorieCreate.html
{% extends 'base.html' %}

{% load static %}
{% block content %}
    <div class="card">
    <div class="row">
        <div class="col-4">
            <img src="{% static "sitepic/active.jpg" %}" class="card-img" alt="girl running image">
        </div>
        <div class="col-8">
            <h5 class="card-title">Calories</h5>
            <form method="post">
                {% csrf_token %}
                    <div type="hidden" class="form-group row">
                        <label type="hidden" for="{{ form.user.id_for_label }}"></label>
                            {{ form.user }}
                    </div>
                    <div class="form-group row">
                        <label for="{{ form.age.id_for_label }}" class="col-2 col-form-label">Age:</label>
                        <div class="col-3">
                            {{ form.age }}
                        </div>
                        <label class="col-2 col-form-label" for="{{ form.sex.id_for_label }}">Gender:</label>
                        <div class="col-3">
                            {{ form.sex }}
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="{{ form.weight.id_for_label }}" class="col-2 col-form-label">Weight:</label>
                        <div class="col-3">
                            {{ form.weight }}
                        </div>
                        <label class="col-2 col-form-label" for="{{ form.weightUnit.id_for_label }}">Weight Unit:</label>
                        <div class="col-3">
                            {{ form.weightUnit }}
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="{{ form.height.id_for_label }}" class="col-2 col-form-label">Height:</label>
                        <div class="col-3">
                            {{ form.height }}
                        </div>
                        <label class="col-2 col-form-label" for="{{ form.heightUnit.id_for_label }}">Height Unit:</label>
                        <div class="col-3">
                            {{ form.heightUnit }}
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="{{ form.activityLevel.id_for_label }}" class="col-2 col-form-label">Activity Level:</label>
                        <div class="col-3">
                            {{ form.activityLevel }}
                        </div>
                    </div>
                    <div class="form-group row justify-content-md-center">
                        <div class="col-2">
                            <input type="submit" value="Submit" class="btn btn-primary" />
                        </div>
                    </div>
                </form>
        </div>
    </div>
</div>
{% endblock %}

templates/create_meal.html
{% extends 'base.html' %}

{% load static %}
{% block content %}
<div class="card">
    <h5 class="card-title">Calories</h5>
    <form method="post">
        {% csrf_token %}
            <div type="hidden" class="form-group row">
                <label type="hidden" for="{{ form.user.id_for_label }}"></label>
                    {{ form.user }}
                <label type="hidden" for="{{ form.day.id_for_label }}"></label>
                    {{ form.day }}
            </div>
            <div class="form-group row">
                <label class="col-2 col-form-label" for="{{ form.meal.id_for_label }}">Meal:</label>
                <div class="col-3">
                    {{ form.meal }}
                </div>
            </div>
            <div class="form-group row">
                <label for="{{ form.food.id_for_label }}" class="col-2 col-form-label">Weight:</label>
                <div class="col-3">
                    {{ form.food }}
                </div>
                <label class="col-2 col-form-label" for="{{ form.servingSize.id_for_label }}">Weight Unit:</label>
                <div class="col-3">
                    {{ form.servingSize }}
                </div>
            </div>
            <div class="form-group row">
                <label for="{{ form.takenPortion.id_for_label }}" class="col-2 col-form-label">Height:</label>
                <div class="col-3">
                    {{ form.takenPortion }}
                </div>
                <label class="col-2 col-form-label" for="{{ form.returnedPortion.id_for_label }}">Height Unit:</label>
                <div class="col-3">
                    {{ form.returnedPortion }}
                </div>
            </div>
            <div class="form-group row justify-content-md-center">
                <div class="col-2">
                    <input type="submit" value="Submit" class="btn btn-primary" />
                </div>
            </div>
    </form>
</div>
{% endblock %}

templates/desc_search.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block extra_head %}
  <style>
    tr[data-href] {
        cursor: pointer;
    }
  </style>
{% endblock %}

{% block content %}
    <div class="col-4">
        <form method="GET" action=".">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label class="card-title">Search food:</label>
                    <input type="search" name="FoodDesc" class="form-control">
                </div>
                <button type="submit" class="btn btn-primary pull-right">Search</button>
                <div class="clearfix"></div>
            </div>
        </div>
        </form>
        <div class="table-responsive">
            <table class="table table-striped table-sm">
                <thead>
                    <tr>
                        <th>Food Code</th>
                        <th>Main Food Description</th>
                        <th>Additional Food Description</th>
                        <th>Refuse</th>
                    </tr>
                </thead>
                <tbody>
                    {% for food in mainfood %}
                        <tr>
                            <td>
                                <a href="{% url 'recurapp:nutrient_search' food.food_code %}">{{ food.food_code }}</a>
                            </td>
                            <td>
                                {{ food.main_food_description }}
                            </td>
                            <td>
                                {% for add in food.AddDescs.all %}
                                    {{ add.additional_food_description }},
                                {% endfor %}
                            </td>
                            <td>
                                <a href="{% url 'recurapp:ndb_search' food.food_code %}">Refuse</a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    <div class="col-8">

    </div>

<script>
var x = 100
    $(document).ready(function() {
        $(document.body).on("click", "tr[data-href]", function () {
            window.location.href = this.dataset.href;
        });
    });
</script>
{% endblock %}

templates/home.html
{% extends 'base.html' %}

{% load static %}
{% block content %}
<div class="card">
    <h5 class="card-title">hi {% if request.user.username == 'travi' %}{{ request.user }}{% endif %}</h5>
</div>
{% endblock %}

templates/ndb_search.html
{% extends 'base.html' %}

{% block content %}
    {% if Food_codes %}
        <h1>Food Codes as Ingredients</h1>
        <div class="table-responsive">
            <table class="table table-striped table-sm">
                <thead>
                    <tr>
                        <th scope="col">Food Code</th>
                        <th scope="col">Main Food Description</th>
                    </tr>
                </thead>
                <tbody>
                    {% for x in Food_codes %}
                        <tr>
                            <td scope="row">{{ x.food_code }}</td>
                            <td>{{ x.main_food_description }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    {% endif %}
    {% if SR_codes %}
        <h1>SR Codes as Ingredients</h1>
        <div class="table-responsive">
            <table class="table table-striped table-sm">
                <thead>
                    <tr>
                        <th scope="col">NDB NO</th>
                        <th scope="col">Long Description</th>
                        <th scope="col">Refuse</th>
                        <th scope="col">Refuse Description</th>
                    </tr>
                </thead>
                <tbody>
                    {% for x in SR_codes %}
                        <tr>
                            <th scope="row">{{ x.ndb_no }}</th>
                            <td>{{ x.long_desc }}</td>
                            <td>{{ x.refuse }}</td>
                            <td>{{ x.ref_desc }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    {% endif %}
    {% if Q_codes %}
    <h1>Question Codes as Ingredients</h1>
    <div class="table-responsive">
    <table class="table table-striped table-sm">
        <thead>
            <tr>
                <th scope="col">What to do with these?</th>
            </tr>
        </thead>
        <tbody>
            {% for x in Q_codes %}
                <th scope="row">{{ x }}</th>
            {% endfor %}
    {% endif %}
{% endblock %}

templates/nutritionFacts.html
<section class="performance-facts">
  <header class="performance-facts__header">
      <div class="container">
          <div class="row">
              <h1 class="performance-facts__title">Nutrition Facts</h1>
          </div>
          <div class="row">
               <h6>{{ main.food_code }}</h6>
          </div>
          <div class="row pb-2">
            <p>{{ main.main_food_description }} {{ mainNutval.0.nutrient_code }}</p>
          </div>
          <div class="row">
              <div class="col-5">
                  <p class="text-left" id="servingSize">Serving Size <span id="servingSizeNum">100</span>g</p>
              </div>
              <div class="col-7">
                  <div class="dropdown show text-right">
              <a class="btn btn-sm btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Measure Description
              </a>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                  <p class="dropdown-item portion" id="portion">100 g - <span class="portion_number">100</span> g</p>
                  {% for weight in main.Weights.all %}
                      <p class="dropdown-item portion" id="portion{{ forloop.counter0 }}">{{ weight.portion_code.portion_description }} - <span class="portion_number{{ forloop.counter0 }}">{{ weight.portion_weight }}</span> g</p>
                  {% endfor %}
              </div>
            </div>
              </div>

          </div>
      </div>
      </header>
      <table class="performance-facts__table">
        <thead>
          <tr>
            <th colspan="3" class="small-info">
              Amount Per Serving
            </th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <th colspan="2">
              <b>Calories</b>
              <span class="nutrient" id="{{ ENERC_KCAL.tagname }}">{{ ENERC_KCAL.value }}</span>
            </th>
            <td>
              Calories from Fat:
              {{ FATTotalCal }}
            </td>
          </tr>
          <tr class="thick-row">
            <td colspan="3" class="small-info">
              <b>% Daily Value*</b>
            </td>
          </tr>
          <tr>
            <th colspan="2">
              <b>Total Fat</b>
                <span class="nutrient" id="{{ FAT.tagname }}">{{ FAT.value }}</span> g
            </th>
            <td>
              <b>{{ FATpercentDaily }}</b>
            </td>
          </tr>
          <tr>
            <td class="blank-cell">
            </td>
            <th>
              Saturated Fat
                <span class="nutrient" id="{{ FASAT.tagname }}">{{ FASAT.value }}</span> g
            </th>
            <td>
              <b>{{ FASATpercentDaily }}</b>
            </td>
          </tr>
          <tr>
            <td class="blank-cell">
            </td>
            <th >
              Trans Fat
              0g
            </th>
            <td>
            </td>
          </tr>
          <tr>
            <th colspan="2">
              <b>Cholesterol</b>
                <span class="nutrient" id="{{ CHOLE.tagname }}">{{ CHOLE.value }}</span> mg
            </th>
            <td>
              <b>18%</b>
            </td>
          </tr>
          <tr>
            <th colspan="2">
              <b>Sodium</b>
                <span class="nutrient" id="{{ NA.tagname }}">{{ NA.value }}</span> mg
            </th>
            <td>
              <b>2%</b>
            </td>
          </tr>
          <tr>
            <th colspan="2">
              <b>Total Carbohydrate</b>
                <span class="nutrient" id="{{ CHOCDF.tagname }}">{{ CHOCDF.value }}</span> g
            </th>
            <td>
              <b>6%</b>
            </td>
          </tr>
          <tr>
            <td class="blank-cell">
            </td>
            <th>
              Dietary Fiber
                <span class="nutrient" id="{{ FIBTG.tagname }}">{{ FIBTG.value }}</span> g
            </th>
            <td>
              <b>4%</b>
            </td>
          </tr>
          <tr>
            <td class="blank-cell">
            </td>
            <th>
              Sugars
                <span class="nutrient" id="{{ SUGAR.tagname }}">{{ SUGAR.value }}</span> g
            </th>
            <td>
            </td>
          </tr>
          <tr class="thick-end">
            <th colspan="2">
              <b>Protein</b>
                <span class="nutrient" id="{{ PROCNT.tagname }}">{{ PROCNT.value }}</span> g
            </th>
            <td>
            </td>
          </tr>
        </tbody>
      </table>

      <table class="performance-facts__table--grid">
        <tbody>
          <tr>
            <td colspan="2">
              Vitamin A
                <span class="nutrient " id="{{ VITA_RAE.tagname }}">{{ VITA_RAE.value }}</span> mcg_RAE
            </td>
            <td>
              Vitamin C
                <span class="nutrient" id="{{ VITC.tagname }}">{{ VITC.value }}</span> mg
            </td>
          </tr>
          <tr class="thin-end">
            <td colspan="2">
              Calcium
                <span class="nutrient" id="{{ CA.tagname }}">{{ CA.value }}</span> mg
            </td>
            <td>
              Iron
                <span class="nutrient" id="{{ FE.tagname }}">{{ FE.value }}</span> mg
            </td>
          </tr>
        </tbody>
      </table>

      <p class="small-info">* Percent Daily Values are based on a {{ calories }} calorie diet.</p>

      <table class="performance-facts__table--small small-info">
        <thead>
          <tr>
            <td colspan="2"></td>
            <th>Calories:</th>
            <th>{{ calories }}</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <th colspan="2">Total Fat</th>
            <td>Less than</td>
            <td>65g</td>
          </tr>
          <tr>
            <td class="blank-cell"></td>
            <th>Saturated Fat</th>
            <td>Less than</td>
            <td>{{ totalFat }}g</td>
          </tr>
          <tr>
            <th colspan="2">Cholesterol</th>
            <td>Less than</td>
            <td>300mg</td>
            <td>300 mg</td>
          </tr>
          <tr>
            <th colspan="2">Sodium</th>
            <td>Less than</td>
            <td>2,400mg</td>
            <td>2,400mg</td>
          </tr>
          <tr>
            <th colspan="3">Total Carbohydrate</th>
            <td>300g</td>
            <td>375g</td>
          </tr>
          <tr>
            <td class="blank-cell"></td>
            <th colspan="2">Dietary Fiber</th>
            <td>25g</td>
            <td>30g</td>
          </tr>
        </tbody>
      </table>

      <p class="small-info">
        Calories per gram:
      </p>
      <p class="small-info text-center">
        Fat 9
        &bull;
        Carbohydrate 4
        &bull;
        Protein 4
      </p>
</section>

{% block extra_scripts %}
<script>
    const portion = document.getElementsByClassName("portion");
    const nutrient = document.getElementsByClassName("nutrient");
    const factslist = ["FE", "CA", "VITC", "VITA_RAE", "PROCNT", "SUGAR", "FIBTG", "CHOCDF", "NA", "CHOLE", "FAT", "FASAT", "ENERC_KCAL"]
    for(let x=0; x<portion.length; x++){
        portion[x].addEventListener("click", function(){
            let portionNum = portion[x].firstElementChild.textContent
            document.getElementById("servingSizeNum").textContent = portionNum.toString()
            for (let i=0; i<nutrientObjs.tagname.length; i++){
                if (factslist.includes(nutrientObjs.tagname[i])) {
                    document.getElementById(nutrientObjs.tagname[i]).textContent = (((nutrientObjs.nutrient_value[i] * portionNum / 100).toFixed(2)).toString())
                }
            }
        })
    };

    function createPortionCodeObj(portion_code, portion_description, portion_weight){
        return {
            portion_code: portion_code,
            portion_description: portion_description,
            portion_weight: portion_weight,
        }
    };

        let portionObj = {
            portion_code:
                {% for weight in main.Weights.all %}
                    {% if forloop.first %}
                        [{{ weight.portion_code.portion_code }},
                    {% elif forloop.last %}
                        {{ weight.portion_code.portion_code }}]
                    {% else %}
                        {{ weight.portion_code.portion_code }},
                    {% endif %}
                {% endfor %},
            portion_description:
                {% for weight in main.Weights.all %}
                    {% if forloop.first %}
                        ["{{ weight.portion_code.portion_description }}",
                    {% elif forloop.last %}
                        "{{ weight.portion_code.portion_description }}"]
                    {% else %}
                        "{{ weight.portion_code.portion_description }}",
                    {% endif %}
                {% endfor %},
            weight:
            {% for weight in main.Weights.all %}
                {% if forloop.first %}
                    [{{ weight.portion_weight }},
                {% elif forloop.last %}
                    {{ weight.portion_weight }}]
                {% else %}
                    {{ weight.portion_weight }},
                {% endif %}
            {% endfor %}
        };

    let nutrientObjs = {
       tagname:
           {% for x in mainNutVal %}
                {% if forloop.first %}
                    ["{{ x.nutrient_code.tagname }}",
                {% elif forloop.last %}
                    "{{ x.nutrient_code.tagname }}"]
                {% else %}
                    "{{ x.nutrient_code.tagname }}",
                {% endif %}
            {% endfor %},
        nutrient_description:
            {% for x in mainNutVal %}
                {% if forloop.first %}
                    ["{{ x.nutrient_code.nutrient_description }}",
                {% elif forloop.last %}
                    "{{ x.nutrient_code.nutrient_description }}"]
                {% else %}
                    "{{ x.nutrient_code.nutrient_description }}",
                {% endif %}
            {% endfor %},
        nutrient_value:
        {% for x in mainNutVal %}
            {% if forloop.first %}
                [{{ x.nutrient_value }},
            {% elif forloop.last %}
                {{ x.nutrient_value }}]
            {% else %}
                {{ x.nutrient_value }},
            {% endif %}
        {% endfor %}
    };
</script>

{% endblock %}

templates/searchWithFacts.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block extra_head %}
    <link href="{% static 'css/nutrition-facts.css' %}" rel="stylesheet">
    <style>
    tr[data-href] {
        cursor: pointer;
    }
    </style>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-4">
            <form method="GET" action=".">
            {% csrf_token %}
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label class="card-title">Search food:</label>
                            <input type="search" name="FoodDesc" class="form-control">
                        </div>
                        <button type="submit" class="btn btn-primary pull-right">Search</button>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </form>
            <div class="table-responsive">
                <table class="table table-striped table-sm">
                    <thead>
                        <tr>
                            <th>Food Code</th>
                            <th>Main Food Description</th>
                            <th>Additional Food Description</th>
                            <th>Refuse</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for food in mainfood %}
                            <tr>
                                <td>
                                    <a href="{% url 'recurapp:nutrient_search' food.food_code %}">{{ food.food_code }}</a>
                                </td>
                                <td>
                                    {{ food.main_food_description }}
                                </td>
                                <td>
                                    {% for add in food.AddDescs.all %}
                                        {{ add.additional_food_description }},
                                    {% endfor %}
                                </td>
                                <td>
                                    <a href="{% url 'recurapp:ndb_search' food.food_code %}">Refuse</a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <div class="col-8">
            {% include "nutritionFacts.html" %}
        </div>
    </div>
{% endblock %}
{% block extra_scripts %}
<script>
var x = 100
    $(document).ready(function() {
        $(document.body).on("click", "tr[data-href]", function () {
            window.location.href = this.dataset.href;
        });
    });
</script>
{% endblock %}

templates/testfilterNODRF.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <form method="get">
        {{ filter.form|crispy  }}
        <input type="submit" />
    </form>
    {% for obj in filter.qs %}
        {{ obj.food_code }} - ${{ obj.main_food_description }}<br />
    {% endfor %}
{% endblock %}